# Based loosely on: https://github.com/actions/starter-workflows/blob/main/ci/terraform.yml

name: 'Terraform'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_and_deploy_infrastructure:
    name: 'Build, Deploy, and Configure Infrastructure'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Clean workspace
      uses: AutoModality/action-clean@v1

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Terraform
      run: ./scripts/run-terraform.sh
      env:
        TF_VAR_do_token: ${{ secrets.do_token }}
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

    - name: Generate Ansible inventory
      run: ./scripts/generate-do-inventory.sh
      env:
        DO_TOKEN: ${{ secrets.do_token }}

    - name: Run Ansible
      run: ./scripts/run-ansible.sh
